language: java
cache:
  directories:
    - $HOME/.m2
before_install:
  - git config user.name "$GIT_NAME"
  - git config user.email "$GIT_EMAIL"
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials
  - gem install asciidoctor
  - ./src/main/bash/travis_install_etcd.sh
install:
- ./mvnw --settings .settings.xml install -P docs -q -U -DskipTests=true -Dmaven.test.redirectTestOutputToFile=true
#- ./docs/src/main/asciidoc/ghpages.sh
script:
- ./etcd-dist/etcd &
- '[ "${TRAVIS_PULL_REQUEST}" != "false" ] || mvn --settings .settings.xml deploy -nsu -Dmaven.test.redirectTestOutputToFile=true'
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] || mvn --settings .settings.xml install -nsu -Dmaven.test.redirectTestOutputToFile=true'
env:
  global:
  - GIT_NAME="Spencer Gibb"
  - GIT_EMAIL=sgibb@pivotal.io
  - CI_DEPLOY_USERNAME=sgibb
  - secure: CU8cBb/DG307+zKh8GpGnxwMxPuDXyPFfV7cZo/S0K/pQ6dZXLSkMx9KJqBPNEgi9kcmRP61aUq98JVpioF984ms7hsUzuPb+DFnayfIMFSsC71gGSpRvIrPRPYp9zy+PMeVpcMY7iy+5/yagsGMjEG9sNqmrfBznx5z3UmvE30=
