version: "3.9"
services:

  #docker exec spring-cloud-etcd /bin/sh -c "/usr/local/bin/etcd --version"
  #docker exec spring-cloud-etcd /bin/sh -c "/usr/local/bin/etcdctl version"
  #docker exec spring-cloud-etcd /bin/sh -c "/usr/local/bin/etcdctl endpoint health"
  #docker exec spring-cloud-etcd /bin/sh -c "/usr/local/bin/etcdctl put foo bar"
  #docker exec spring-cloud-etcd /bin/sh -c "/usr/local/bin/etcdctl get foo"
  #docker exec spring-cloud-etcd /bin/sh -c "/usr/local/bin/etcdutl version"

  etcd:
    image: "gcr.io/etcd-development/etcd:v3.5.1"
    container_name: "spring-cloud-etcd"
    volumes:
      - etcd-data:/etcd-data
    command: [
        "etcd",
        "--name=s1",
        "--data-dir=/etcd-data",
        "--listen-client-urls=http://0.0.0.0:2379",
        "--advertise-client-urls=http://0.0.0.0:2379",
        "--listen-peer-urls=http://0.0.0.0:2380",
        "--initial-advertise-peer-urls=http://0.0.0.0:2380",
        "--initial-cluster=s1=http://0.0.0.0:2380",
        "--initial-cluster-token=tkn",
        "--initial-cluster-state=new",
        "--log-level=info",
        "--logger=zap",
        "--log-outputs=stderr"
    ]
    ports:
      - "2379:2379"
      - "2380:2380"

volumes:
  etcd-data: