spring:
  application:
    name: testEtcdApp
  cloud:
    etcd:
      discovery:
        port: 8080
server:
  port: 8080

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true
